# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Lost',
        ),
    ]
