# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lost_found', '0005_lost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
