# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('branch', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.CharField(blank=True, default='', max_length=100)),
                ('hostel', models.CharField(choices=[('0', 'S.N.Bose '), ('1', 'Aryabhatta '), ('2', 'S. Ramanujan '), ('3', 'C. V. Raman'), ('4', 'Morvi'), ('5', 'Dhanrajgiri'), ('6', 'Rajputana'), ('7', 'Limbdi'), ('8', 'S.C. De'), ('9', 'Vishweshvarayya'), ('10', 'Vivekanand'), ('11', 'Vishwakarma'), ('12', 'Gandhi Smriti Mahila Chhatravas'), ('13', 'New Girls GSMC Extn.'), ('14', 'Saluja')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
