# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0002_auto_20170713_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hostel',
            field=models.CharField(blank=True, choices=[('0', 'S.N.Bose '), ('1', 'Aryabhatta '), ('2', 'S. Ramanujan '), ('3', 'C. V. Raman'), ('4', 'Morvi'), ('5', 'Dhanrajgiri'), ('6', 'Rajputana'), ('7', 'Limbdi'), ('8', 'S.C. De'), ('9', 'Vishweshvarayya'), ('10', 'Vivekanand'), ('11', 'Vishwakarma'), ('12', 'Gandhi Smriti Mahila Chhatravas'), ('13', 'New Girls GSMC Extn.'), ('14', 'Saluja')], default='0', max_length=100, null=True),
        ),
    ]
