# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0003_auto_20170713_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hostel',
        ),
    ]
