# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0005_auto_20170714_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='bio',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
