# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0006_auto_20170714_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, choices=[('0', 'Bio-Chemical Engg.'), ('1', 'Bio-Medical Engg'), ('2', 'Ceramic Engg.'), ('3', 'Chemical Engg.'), ('4', 'Chemistry'), ('5', 'Civil Engg.'), ('6', 'Computer Engg.'), ('7', 'Electrical Engg.'), ('8', 'Electronic Engg.'), ('9', 'Material Sc. and Tech.'), ('10', 'Mathematical Sciences'), ('11', 'Mechanical Engg.'), ('12', 'Metallurgical Engg.'), ('13', 'Mining Engg.'), ('14', 'Pharmaceutical Engineering & Technology'), ('15', 'Physics')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(blank=True, choices=[('0', '1st'), ('1', '2nd'), ('2', '3rd'), ('3', '4th'), ('4', '5th')], default='', max_length=100),
        ),
    ]
