# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('por', '0008_auto_20170714_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
